name: fullcycle

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./node:/app
      - /app/node_modules

  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
